### ISSUE TITLE
Alpine dragon breeding crash on my sever.

### ISSUE THREAD

**Issue by ItsAlvo** [Syrikal/Wyrmroost-Patch#3]
I'm having an issue when trying to breed Alpine Dragons (using Wyrmroost Patch, honey treat) it crashes the server. I have a log of the crash if needed. just struggling to figure out what it is

[crash-2023-01-18_19.11.31-server.txt](https://github.com/Syrikal/Wyrmroost-Patch/files/10459707/crash-2023-01-18_19.11.31-server.txt)

**Comment by Syrikal** [comment]
Fixed in 1.2.
